# This shows a repository which has a secret attached for git provider operation.
---
apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sample-app-via-direct-webhook
  namespace: "sample-ci"
spec:
  # which URL this Repository handles
  url: "https://github.com/owner/sample-ci-direct-webhook"
  git_provider:
    url: "github.enteprise.company.com"
    secret:
      name: "github.enteprise.personal.access.token"
      key: "tokenkey"
    webhook_secret:
      name: "github-webhook-config"
      key: "webhook.secret"
