coverage:
  # Commit status https://docs.codecov.io/docs/commit-status are used
  # to block PR based on coverage threshold.
  status:
    project:
      default:
        target: auto
        threshold: 5%
    patch:
      # Disable the coverage threshold of the patch, so that PRs are
      # only failing because of overall project coverage threshold.
      # See https://docs.codecov.io/docs/commit-status#disabling-a-status.
      default: false

ignore:
  - "**/zz_generated*.go"
  - "**/*.pb.go"
  - "hack"
  - "pkg/generated"
  - "pkg/apis"
  - "cmd/*"
  - "test"
  - "third_party"
  - "vendor"
